name: Generate Snake

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Clona o repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - name: Gerar animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: EnzoRibeir
          svg_out_path: dist/github-snake.svg

      # Faz o deploy no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
